name: Discord Notify

on:
  push:
  pull_request:
    types: [opened, synchronize, closed]
  create:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Discord
        uses: Ilshidur/action-discord@0.4.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            ğŸš€ GitHubã‚¤ãƒ™ãƒ³ãƒˆé€šçŸ¥ï¼
            Repository: ${{ github.repository }}
            Author: ${{ github.actor }}
            Event: ${{ github.event_name }}
            Branch/Ref: ${{ github.ref }}
            Title: ${{ github.event.pull_request.title }}
